/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "AGCCloudDBObjectTypeHeaders.h"

static const long ObjectTypeVersion = 30;

static const int FormatVersion = 1;

@implementation AGCCloudDBObjectTypeInfoHelper

+ (AGCCloudDBObjectTypeInfo *)obtainObjectTypeInfo {
    return [[AGCCloudDBObjectTypeInfo alloc] initWithObjectTypes:@[FollowUser.class,
                                                                   LikePost.class,
                                                                   Message.class,
                                                                   Post.class,
                                                                   RecentMessage.class,
                                                                   UserInfo.class]
                                               objectTypeVersion:ObjectTypeVersion
                                                   formatVersion:FormatVersion];
}

@end
