/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "AGCCloudDBObjectTypeInfoHelper.h"
#import "FollowUser.h"
#import "LikePost.h"
#import "Message.h"
#import "Post.h"
#import "RecentMessage.h"
#import "UserInfo.h"

