/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "FollowUser.h"

@implementation FollowUser

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"followerUser",
             @"followingUser"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"followerUser" : @[@"followerUser"],
              @"followingUser" : @[@"followingUser"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"followerUser",
             @"followingUser"];
}

@end
