/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "LikePost.h"

@implementation LikePost

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"postId",
             @"userUid"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"postId" : @[@"postId"],
              @"userUid" : @[@"userUid"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"postId",
             @"userUid"];
}

@end
