/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "Message.h"

@implementation Message

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"id"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"fromUserUid" : @[@"fromUserUid"],
              @"id" : @[@"id"],
              @"timestamp" : @[@"timestamp"],
              @"toUserUid" : @[@"toUserUid"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"id"];
}

@end
