/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface Message : AGCCloudDBObject
@property (nonatomic, copy) NSString *id;
@property (nonatomic, copy) NSString *fromUserUid;
@property (nonatomic, copy) NSString *toUserUid;
@property (nonatomic, strong) AGCCloudDBText *message;
@property (nonatomic, strong) NSDate *timestamp;
@end

NS_ASSUME_NONNULL_END