/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface Post : AGCCloudDBObject
@property (nonatomic, copy) NSString *id;
@property (nonatomic, copy) NSString *userUid;
@property (nonatomic, strong) AGCCloudDBText *caption;
@property (nonatomic, strong) NSDate *timeStamp;
@property (nonatomic, strong) NSNumber<AGCInt> *likeCount;
@end

NS_ASSUME_NONNULL_END