/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "RecentMessage.h"

@implementation RecentMessage

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"fromUserUid",
             @"toUserUid"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"fromUserUid" : @[@"fromUserUid"],
              @"toUserUid" : @[@"toUserUid"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"fromUserUid",
             @"toUserUid"];
}

@end
