/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface UserInfo : AGCCloudDBObject
@property (nonatomic, copy) NSString *uid;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *username;
@property (nonatomic, copy) NSString *fullName;
@property (nonatomic, copy) NSString *profileImageUrl;
@property (nonatomic, strong) NSNumber<AGCInt> *followersCount;
@property (nonatomic, strong) NSNumber<AGCInt> *followingCount;
@property (nonatomic, copy) NSString *pushToken;
@end

NS_ASSUME_NONNULL_END