/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "UserInfo.h"

@implementation UserInfo

- (instancetype)init {
    self = [super init];
    if (self) {
        _followersCount = @0;
        _followingCount = @0;
    }
    return self;
}

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"uid"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"email" : @[@"email"]};
}

+ (NSDictionary *)defaultValueProperties {
    return @{@"followersCount" : @0,
             @"followingCount" : @0};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"uid",
             @"followersCount",
             @"followingCount"];
}

@end
